#!/bin/bash
# Phase 2: Pipeline sequencing enforcement
# PreToolUse hook on Agent
#
# Reads docs/pipeline/pipeline-state.md to determine current phase.
# Blocks out-of-order agent invocations. Enforces the mandatory gates
# from Eva's persona (the ones marked "same severity as editing source code").
#
# Only enforces from the main thread (Eva). Subagents spawning other
# subagents is already blocked by disallowedTools: Agent.

set -euo pipefail
[ "${ATELIER_SETUP_MODE:-}" = "1" ] && exit 0
[ -f "${CLAUDE_PROJECT_DIR:-.}/docs/pipeline/.setup-mode" ] && exit 0

INPUT=$(cat)

if ! command -v jq &>/dev/null; then
  echo "ERROR: jq is required for atelier-pipeline hooks. Install: brew install jq" >&2
  exit 2
fi

TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // empty')
[ "$TOOL_NAME" != "Agent" ] && exit 0

# Only enforce from main thread (Eva orchestrates)
AGENT_ID=$(echo "$INPUT" | jq -r '.agent_id // empty')
[ -n "$AGENT_ID" ] && exit 0

SUBAGENT_TYPE=$(echo "$INPUT" | jq -r '.tool_input.subagent_type // empty')
[ -z "$SUBAGENT_TYPE" ] && exit 0

# Load config
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="$SCRIPT_DIR/enforcement-config.json"
[ ! -f "$CONFIG" ] && exit 0

# Ensure CWD is the project root — hooks may inherit an arbitrary CWD
PROJECT_ROOT="${CURSOR_PROJECT_DIR:-${CLAUDE_PROJECT_DIR:-$(cd "$SCRIPT_DIR/../.." && pwd)}}"
cd "$PROJECT_ROOT"

# Source shared hook library (ADR-0034 Wave 2 Step 2.1)
if [ -f "$SCRIPT_DIR/hook-lib.sh" ]; then
  source "$SCRIPT_DIR/hook-lib.sh" 2>/dev/null || true
fi

PIPELINE_DIR=$(jq -r '.pipeline_state_dir' "$CONFIG")
STATE_FILE="$PIPELINE_DIR/pipeline-state.md"

# ─── Roster-aware helper ───────────────────────────────────────────────────
# Returns 0 (true) when the agent is enabled in the active roster, or when
# the roster key is absent/malformed (fail-open per ADR-0060).
roster_agent_enabled() {
  local agent_name="$1"
  # Try .cursor/ first (Cursor), fall back to .claude/ (Claude Code)
  local roster_config
  if [ -f "${PROJECT_ROOT}/.cursor/pipeline-config.json" ]; then
    roster_config="${PROJECT_ROOT}/.cursor/pipeline-config.json"
  else
    roster_config="${PROJECT_ROOT}/.claude/pipeline-config.json"
  fi
  if [ ! -f "$roster_config" ]; then
    return 0  # fail-open: no config means treat as enabled
  fi
  # Fail-open when agent_roster key is entirely absent (upgrade path from v5).
  # When agent_roster IS present, an agent absent from it is treated as disabled.
  local roster_present
  roster_present=$(jq -r 'if .agent_roster then "yes" else "no" end' \
    "$roster_config" 2>/dev/null) || true
  if [ "${roster_present:-no}" = "no" ]; then
    return 0  # fail-open: no roster means old install, treat all agents as enabled
  fi
  local enabled
  # Use explicit false comparison: jq's // alternative ignores false (falsy).
  # When the agent key is absent from the roster, treat as disabled (user didn't select it).
  enabled=$(jq -r --arg agent "$agent_name" \
    'if .agent_roster[$agent] == null then "false" elif .agent_roster[$agent].enabled == false then "false" else "true" end' \
    "$roster_config" 2>/dev/null) || true
  # fail-open: any jq error -> enabled
  [ "${enabled:-true}" != "false" ]
}

# ─── Snapshot state file to avoid partial-read race ───────────────────
# Eva may be mid-write to pipeline-state.md when this hook fires.
# Copying to a temp file gives a consistent snapshot for parsing.
STATE_SNAPSHOT=$(mktemp)
trap 'rm -f "$STATE_SNAPSHOT"' EXIT
cp "$STATE_FILE" "$STATE_SNAPSHOT" 2>/dev/null || { rm -f "$STATE_SNAPSHOT"; exit 0; }

# ─── Structured state parser (delegates to hook-lib.sh) ──────────────
# Reads the machine-readable PIPELINE_STATUS JSON marker from the snapshot.
# Format: <!-- PIPELINE_STATUS: {"qa_status": "PASS", "phase": "review", "timestamp": "..."} -->
# Returns empty string if marker is absent or JSON is malformed.
parse_pipeline_status() {
  local field="$1"
  hook_lib_pipeline_status_field "$field" < "$STATE_SNAPSHOT"
}

# ─── Gate 0b: Investigator must be directed to the configured worktree ─
# When the pipeline state carries a non-null worktree_path, any investigator
# invocation prompt must reference that path. Otherwise the investigator
# would read files from the wrong location (main repo instead of worktree).
# Fails open when worktree_path is empty/absent.
if [ "$SUBAGENT_TYPE" = "investigator" ] && roster_agent_enabled "investigator"; then
  WORKTREE_PATH=$(parse_pipeline_status "worktree_path") || true
  if [ -n "$WORKTREE_PATH" ] && [ "$WORKTREE_PATH" != "null" ]; then
    INVOCATION_PROMPT=$(echo "$INPUT" | jq -r '.tool_input.prompt // empty')
    # Note: worktree_path must be a clean absolute path (no glob chars). Paths
    # from pipeline-state.md are generated by Eva from `git worktree add` output
    # and are safe. The substring match below relies on this invariant.
    case "$INVOCATION_PROMPT" in
      *"$WORKTREE_PATH"*)
        : # prompt correctly references the worktree
        ;;
      *)
        echo "BLOCKED: Cannot invoke investigator — pipeline carries worktree_path '$WORKTREE_PATH' but the invocation prompt does not reference it. The investigator would read files from the wrong location. Include the worktree path in the prompt." >&2
        exit 2
        ;;
    esac
  fi
fi

# ─── Gate 0: Ellis blocked when git is not available ────────────────
# When git_available: false in pipeline-config.json, Ellis cannot operate
# (no git repo to commit to). Block with a clear message.
# Roster check: if Ellis is not in the roster, skip all Ellis gates.
if [ "$SUBAGENT_TYPE" = "ellis" ] && ! roster_agent_enabled "ellis"; then
  exit 0
fi
if [ "$SUBAGENT_TYPE" = "ellis" ]; then
  # Try .cursor/ first (Cursor), fall back to .claude/ (Claude Code)
  if [ -f "${PROJECT_ROOT}/.cursor/pipeline-config.json" ]; then
    PIPELINE_CONFIG="${PROJECT_ROOT}/.cursor/pipeline-config.json"
  else
    PIPELINE_CONFIG="${PROJECT_ROOT}/.claude/pipeline-config.json"
  fi
  if [ -f "$PIPELINE_CONFIG" ]; then
    GIT_AVAILABLE=$(jq -r 'if .git_available == false then "false" else "true" end' "$PIPELINE_CONFIG" 2>/dev/null) || true
    if [ "$GIT_AVAILABLE" = "false" ]; then
      echo "BLOCKED: Ellis is unavailable -- no git repository configured. Files were written directly to disk." >&2
      exit 2
    fi
  fi
fi

# ─── Gate 1: Ellis requires Poirot verification PASS during active pipelines ─────
# "Ellis commits. Eva does not." + "Poirot verifies every Colby output."
# During an active pipeline, Ellis cannot be invoked unless qa_status is PASS.
# Outside an active pipeline (no state file, no marker, idle/complete phase),
# Ellis is allowed through for infrastructure, doc-only, and setup commits.
if [ "$SUBAGENT_TYPE" = "ellis" ]; then
  # No pipeline-state.md -> no active pipeline -> allow
  if [ ! -f "$STATE_FILE" ]; then
    exit 0
  fi

  # No PIPELINE_STATUS marker -> no active pipeline -> allow
  PHASE=$(parse_pipeline_status "phase") || true
  if [ -z "$PHASE" ]; then
    exit 0
  fi

  # Normalize phase to lowercase for comparison
  PHASE=$(echo "$PHASE" | tr '[:upper:]' '[:lower:]')

  # Inactive phases -> allow (pipeline not running).
  # "none" is included because PIPELINE_STATUS may carry phase:none when the state file
  # exists but no pipeline has been activated yet. Without this, Ellis falls through to
  # the Poirot verification enforcement and gets blocked with "pipeline is active (phase: none)".
  if [ "$PHASE" = "idle" ] || [ "$PHASE" = "complete" ] || [ "$PHASE" = "none" ]; then
    exit 0
  fi

  # Micro pipelines skip Poirot -- test suite is the safety valve
  SIZING=$(parse_pipeline_status "sizing") || true
  SIZING=$(echo "$SIZING" | tr '[:upper:]' '[:lower:]')
  if [ "$SIZING" = "micro" ]; then
    exit 0
  fi

  # CI Watch fix cycle: if ci_watch_active=true and qa_status=CI_VERIFIED, allow Ellis
  # CI_VERIFIED is distinct from PASS -- written by Eva after Poirot verifies a CI fix
  CI_WATCH_ACTIVE=$(parse_pipeline_status "ci_watch_active") || true
  QA_STATUS=$(parse_pipeline_status "qa_status") || true
  if [ "$CI_WATCH_ACTIVE" = "true" ] && [ "$QA_STATUS" = "CI_VERIFIED" ]; then
    exit 0
  fi

  # Active phase -> enforce Poirot verification PASS
  if [ "$QA_STATUS" != "PASS" ]; then
    echo "BLOCKED: Cannot invoke Ellis — pipeline is active (phase: $PHASE) but no Poirot verification PASS found. Poirot must verify Colby's output before committing." >&2
    exit 2
  fi
fi

# ─── Gate 2: Agatha after Poirot, not during build ─────────────────────
# "Agatha writes docs after final Poirot review, not during build."
# Uses the structured PIPELINE_STATUS phase field instead of grep.
if [ "$SUBAGENT_TYPE" = "agatha" ] && roster_agent_enabled "agatha"; then
  if [ -f "$STATE_FILE" ]; then
    CURRENT_PHASE=$(parse_pipeline_status "phase") || true
    CURRENT_PHASE=$(echo "$CURRENT_PHASE" | tr '[:upper:]' '[:lower:]')
    if [ "$CURRENT_PHASE" = "build" ] || [ "$CURRENT_PHASE" = "implement" ]; then
      echo "BLOCKED: Cannot invoke Agatha during the build phase. Agatha writes docs after Poirot's final sweep against verified code." >&2
      exit 2
    fi
  fi
fi

# ── Gate 3: Ellis requires telemetry capture at pipeline end ───────────
# Eva must capture T3 telemetry (set telemetry_captured: true in PIPELINE_STATUS)
# before the final Ellis commit. T3 is a pipeline-level aggregate (rework rate,
# EvoScore, phase durations) that requires the full pipeline to compute.
# Per-wave commits during the build phase are exempt -- T3 doesn't exist yet.
if [ "$SUBAGENT_TYPE" = "ellis" ]; then
  if [ -f "$STATE_FILE" ]; then
    PHASE=$(parse_pipeline_status "phase") || true
    PHASE=$(echo "$PHASE" | tr '[:upper:]' '[:lower:]')

    # Only enforce after the build phase (review, reconciliation, docs).
    # During build, per-wave commits are gated by qa_status + poirot_reviewed only.
    # "none" is excluded alongside idle/complete — same inactive-phase treatment as Gate 1.
    if [ -n "$PHASE" ] && [ "$PHASE" != "idle" ] && [ "$PHASE" != "complete" ] && [ "$PHASE" != "none" ] && [ "$PHASE" != "build" ] && [ "$PHASE" != "test-authoring" ] && [ "$PHASE" != "design" ]; then
      SIZING=$(parse_pipeline_status "sizing") || true
      SIZING=$(echo "$SIZING" | tr '[:upper:]' '[:lower:]')
      # Only enforce when sizing is explicitly set to a non-micro value.
      # When sizing is absent, the pipeline size is unknown -- fail open.
      if [ -n "$SIZING" ] && [ "$SIZING" != "micro" ]; then
        # CI Watch fix cycles are exempt (they have their own flow)
        CI_WATCH=$(parse_pipeline_status "ci_watch_active") || true
        if [ "$CI_WATCH" != "true" ]; then
          TELEMETRY=$(parse_pipeline_status "telemetry_captured") || true
          if [ "$TELEMETRY" != "true" ]; then
            echo "BLOCKED: Cannot invoke Ellis — pipeline is at phase '$PHASE' but telemetry has not been captured. Eva must capture T3 telemetry before the final commit." >&2
            exit 2
          fi
        fi
      fi
    fi
  fi
fi

# ─── Gate 4 (formerly Gate 3): No git commands from main thread ──────
# "Eva never runs git add, git commit, or git push on code changes."
# This gate catches Eva trying to use Bash for git operations instead
# of invoking Ellis. Checked via the Bash hook below, not here.
# (This hook only fires on the Agent tool.)

# ─── Gate 4 (old note): Removed ───────────────────────────────────────
# Previously checked if Colby was invoked for "build" without an ADR.
# Removed: keyword matching on prompts was fragile, and ADR file naming
# varies by project. The real enforcement is Gate 1 (Ellis requires Poirot
# QA PASS) — if Colby builds something bad, it can't ship without QA.

# ─── Gate 4: Ellis requires Poirot review during active pipelines ─────
# "Poirot blind-reviews every wave. Skipping Poirot is the same class
# of violation as skipping Poirot." (pipeline-orchestration.md mandatory gate 5)
# During an active pipeline, Ellis cannot be invoked unless poirot_reviewed
# is true. Micro pipelines and CI Watch fix cycles are exempt.
if [ "$SUBAGENT_TYPE" = "ellis" ]; then
  if [ -f "$STATE_FILE" ]; then
    PHASE=$(parse_pipeline_status "phase") || true
    PHASE=$(echo "$PHASE" | tr '[:upper:]' '[:lower:]')

    # "none" is excluded alongside idle/complete — same inactive-phase treatment as Gate 1.
    if [ -n "$PHASE" ] && [ "$PHASE" != "idle" ] && [ "$PHASE" != "complete" ] && [ "$PHASE" != "none" ]; then
      SIZING=$(parse_pipeline_status "sizing") || true
      SIZING=$(echo "$SIZING" | tr '[:upper:]' '[:lower:]')
      # Only enforce when sizing is explicitly set to a non-micro value.
      # When sizing is absent, the pipeline size is unknown -- fail open.
      if [ -n "$SIZING" ] && [ "$SIZING" != "micro" ]; then
        # CI Watch fix cycles are exempt (they have their own flow)
        CI_WATCH=$(parse_pipeline_status "ci_watch_active") || true
        if [ "$CI_WATCH" != "true" ]; then
          POIROT_REVIEWED=$(parse_pipeline_status "poirot_reviewed") || true
          if [ "$POIROT_REVIEWED" != "true" ]; then
            echo "BLOCKED: Cannot invoke Ellis — pipeline is active (phase: $PHASE) but Poirot has not reviewed. Poirot must blind-review every wave before committing." >&2
            exit 2
          fi
        fi
      fi
    fi
  fi
fi

# ─── Gate 5: Ellis requires Robert review on Medium/Large ─────────────
# "Robert-subagent reviews at the review juncture (Medium/Large).
# Skipping Robert-subagent on Medium/Large is the same class of violation
# as skipping Poirot." (pipeline-orchestration.md mandatory gate 7)
# Only enforces at the review phase on medium/large pipelines.
# CI Watch fix cycles are exempt.
if [ "$SUBAGENT_TYPE" = "ellis" ]; then
  if [ -f "$STATE_FILE" ]; then
    PHASE=$(parse_pipeline_status "phase") || true
    PHASE=$(echo "$PHASE" | tr '[:upper:]' '[:lower:]')
    SIZING=$(parse_pipeline_status "sizing") || true
    SIZING=$(echo "$SIZING" | tr '[:upper:]' '[:lower:]')

    # Only enforce during review phase on medium or large pipelines
    if [ "$PHASE" = "review" ] && { [ "$SIZING" = "medium" ] || [ "$SIZING" = "large" ]; }; then
      # CI Watch fix cycles are exempt
      CI_WATCH=$(parse_pipeline_status "ci_watch_active") || true
      if [ "$CI_WATCH" != "true" ]; then
        # Amendment: if the product specs directory is absent or contains no
        # .md files, the Robert-review requirement is vestigial — there is
        # no spec to accept. Skip the block when no .md specs are present
        # (find on an absent path returns zero results cleanly).
        # product_specs_dir lives in pipeline-config.json (not enforcement-config.json),
        # following the same .cursor/ -> .claude/ precedence as Gate 0.
        if [ -f "${PROJECT_ROOT}/.cursor/pipeline-config.json" ]; then
          GATE5_PIPELINE_CONFIG="${PROJECT_ROOT}/.cursor/pipeline-config.json"
        else
          GATE5_PIPELINE_CONFIG="${PROJECT_ROOT}/.claude/pipeline-config.json"
        fi
        PRODUCT_SPECS_DIR=$(jq -r '.product_specs_dir // "docs/product"' "$GATE5_PIPELINE_CONFIG" 2>/dev/null || echo "docs/product")
        PRODUCT_SPECS_DIR=${PRODUCT_SPECS_DIR:-docs/product}
        # -maxdepth 1 restricts the count to direct children so README.md
        # and archived specs in subdirectories do not satisfy "spec exists".
        SPEC_COUNT=$(find "${PROJECT_ROOT}/${PRODUCT_SPECS_DIR}" -maxdepth 1 -name "*.md" 2>/dev/null | wc -l | tr -d ' ' || true)
        SPEC_COUNT=${SPEC_COUNT:-0}
        if [ "$SPEC_COUNT" = "0" ]; then
          exit 0
        fi

        ROBERT_REVIEWED=$(parse_pipeline_status "robert_reviewed") || true
        if [ "$ROBERT_REVIEWED" != "true" ]; then
          echo "BLOCKED: Cannot invoke Ellis — pipeline is in review phase (sizing: $SIZING) but Robert has not reviewed. Robert must review at the review juncture on Medium/Large pipelines." >&2
          exit 2
        fi
      fi
    fi
  fi
fi

exit 0
